/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckJobIdRouteImport } from './routes/deck/$jobId'
import { Route as ProcessJobIdRouteImport } from './routes/process/$jobId'
import { Route as ScenesJobIdRouteImport } from './routes/scenes/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckJobIdRoute = DeckJobIdRouteImport.update({
  id: '/deck/$jobId',
  path: '/deck/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessJobIdRoute = ProcessJobIdRouteImport.update({
  id: '/process/$jobId',
  path: '/process/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesJobIdRoute = ScenesJobIdRouteImport.update({
  id: '/scenes/$jobId',
  path: '/scenes/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$jobId': typeof DeckJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/scenes/$jobId': typeof ScenesJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$jobId': typeof DeckJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/scenes/$jobId': typeof ScenesJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$jobId': typeof DeckJobIdRoute
  '/process/$jobId': typeof ProcessJobIdRoute
  '/scenes/$jobId': typeof ScenesJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$jobId' | '/process/$jobId' | '/scenes/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$jobId' | '/process/$jobId' | '/scenes/$jobId'
  id: '__root__' | '/' | '/deck/$jobId' | '/process/$jobId' | '/scenes/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckJobIdRoute: typeof DeckJobIdRoute
  ProcessJobIdRoute: typeof ProcessJobIdRoute
  ScenesJobIdRoute: typeof ScenesJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$jobId': {
      id: '/deck/$jobId'
      path: '/deck/$jobId'
      fullPath: '/deck/$jobId'
      preLoaderRoute: typeof DeckJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/$jobId': {
      id: '/process/$jobId'
      path: '/process/$jobId'
      fullPath: '/process/$jobId'
      preLoaderRoute: typeof ProcessJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/$jobId': {
      id: '/scenes/$jobId'
      path: '/scenes/$jobId'
      fullPath: '/scenes/$jobId'
      preLoaderRoute: typeof ScenesJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckJobIdRoute: DeckJobIdRoute,
  ProcessJobIdRoute: ProcessJobIdRoute,
  ScenesJobIdRoute: ScenesJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
